/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalTutorRouteImport } from './routes/portal/tutor'
import { Route as PortalLogoutRouteImport } from './routes/portal/logout'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalAdminRouteImport } from './routes/portal/admin'
import { Route as PortalTutorsIndexRouteImport } from './routes/portal/tutors/index'
import { Route as PortalTutorIndexRouteImport } from './routes/portal/tutor/index'
import { Route as PortalStudentsIndexRouteImport } from './routes/portal/students/index'
import { Route as PortalOnboardingIndexRouteImport } from './routes/portal/onboarding/index'
import { Route as PortalAdminIndexRouteImport } from './routes/portal/admin/index'
import { Route as PortalTutorsTutorIdRouteImport } from './routes/portal/tutors/$tutorId'
import { Route as PortalTutorProfileRouteImport } from './routes/portal/tutor/profile'
import { Route as PortalTutorAvailabilityRouteImport } from './routes/portal/tutor/availability'
import { Route as PortalStudentsStudentIdRouteImport } from './routes/portal/students/$studentId'
import { Route as PortalSettingsAccountRouteImport } from './routes/portal/settings/account'
import { Route as PortalRegisterSplatRouteImport } from './routes/portal/register.$'
import { Route as PortalOnboardingStudentRouteImport } from './routes/portal/onboarding/student'
import { Route as PortalOnboardingPaymentRouteImport } from './routes/portal/onboarding/payment'
import { Route as PortalLoginSplatRouteImport } from './routes/portal/login.$'
import { Route as PortalForgotPasswordSplatRouteImport } from './routes/portal/forgot-password.$'
import { Route as PortalAdminTutorsIndexRouteImport } from './routes/portal/admin/tutors/index'
import { Route as PortalAdminTutorsTutorIdRouteImport } from './routes/portal/admin/tutors/$tutorId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTutorRoute = PortalTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogoutRoute = PortalLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTutorsIndexRoute = PortalTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTutorIndexRoute = PortalTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTutorRoute,
} as any)
const PortalStudentsIndexRoute = PortalStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingIndexRoute = PortalOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminIndexRoute = PortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalTutorsTutorIdRoute = PortalTutorsTutorIdRouteImport.update({
  id: '/tutors/$tutorId',
  path: '/tutors/$tutorId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTutorProfileRoute = PortalTutorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalTutorRoute,
} as any)
const PortalTutorAvailabilityRoute = PortalTutorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => PortalTutorRoute,
} as any)
const PortalStudentsStudentIdRoute = PortalStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsAccountRoute = PortalSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRegisterSplatRoute = PortalRegisterSplatRouteImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingStudentRoute = PortalOnboardingStudentRouteImport.update({
  id: '/onboarding/student',
  path: '/onboarding/student',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingPaymentRoute = PortalOnboardingPaymentRouteImport.update({
  id: '/onboarding/payment',
  path: '/onboarding/payment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginSplatRoute = PortalLoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => PortalRoute,
} as any)
const PortalForgotPasswordSplatRoute =
  PortalForgotPasswordSplatRouteImport.update({
    id: '/forgot-password/$',
    path: '/forgot-password/$',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAdminTutorsIndexRoute = PortalAdminTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminTutorsTutorIdRoute =
  PortalAdminTutorsTutorIdRouteImport.update({
    id: '/tutors/$tutorId',
    path: '/tutors/$tutorId',
    getParentRoute: () => PortalAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/logout': typeof PortalLogoutRoute
  '/portal/tutor': typeof PortalTutorRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/forgot-password/$': typeof PortalForgotPasswordSplatRoute
  '/portal/login/$': typeof PortalLoginSplatRoute
  '/portal/onboarding/payment': typeof PortalOnboardingPaymentRoute
  '/portal/onboarding/student': typeof PortalOnboardingStudentRoute
  '/portal/register/$': typeof PortalRegisterSplatRoute
  '/portal/settings/account': typeof PortalSettingsAccountRoute
  '/portal/students/$studentId': typeof PortalStudentsStudentIdRoute
  '/portal/tutor/availability': typeof PortalTutorAvailabilityRoute
  '/portal/tutor/profile': typeof PortalTutorProfileRoute
  '/portal/tutors/$tutorId': typeof PortalTutorsTutorIdRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/onboarding/': typeof PortalOnboardingIndexRoute
  '/portal/students/': typeof PortalStudentsIndexRoute
  '/portal/tutor/': typeof PortalTutorIndexRoute
  '/portal/tutors/': typeof PortalTutorsIndexRoute
  '/portal/admin/tutors/$tutorId': typeof PortalAdminTutorsTutorIdRoute
  '/portal/admin/tutors/': typeof PortalAdminTutorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/logout': typeof PortalLogoutRoute
  '/portal': typeof PortalIndexRoute
  '/portal/forgot-password/$': typeof PortalForgotPasswordSplatRoute
  '/portal/login/$': typeof PortalLoginSplatRoute
  '/portal/onboarding/payment': typeof PortalOnboardingPaymentRoute
  '/portal/onboarding/student': typeof PortalOnboardingStudentRoute
  '/portal/register/$': typeof PortalRegisterSplatRoute
  '/portal/settings/account': typeof PortalSettingsAccountRoute
  '/portal/students/$studentId': typeof PortalStudentsStudentIdRoute
  '/portal/tutor/availability': typeof PortalTutorAvailabilityRoute
  '/portal/tutor/profile': typeof PortalTutorProfileRoute
  '/portal/tutors/$tutorId': typeof PortalTutorsTutorIdRoute
  '/portal/admin': typeof PortalAdminIndexRoute
  '/portal/onboarding': typeof PortalOnboardingIndexRoute
  '/portal/students': typeof PortalStudentsIndexRoute
  '/portal/tutor': typeof PortalTutorIndexRoute
  '/portal/tutors': typeof PortalTutorsIndexRoute
  '/portal/admin/tutors/$tutorId': typeof PortalAdminTutorsTutorIdRoute
  '/portal/admin/tutors': typeof PortalAdminTutorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/logout': typeof PortalLogoutRoute
  '/portal/tutor': typeof PortalTutorRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/forgot-password/$': typeof PortalForgotPasswordSplatRoute
  '/portal/login/$': typeof PortalLoginSplatRoute
  '/portal/onboarding/payment': typeof PortalOnboardingPaymentRoute
  '/portal/onboarding/student': typeof PortalOnboardingStudentRoute
  '/portal/register/$': typeof PortalRegisterSplatRoute
  '/portal/settings/account': typeof PortalSettingsAccountRoute
  '/portal/students/$studentId': typeof PortalStudentsStudentIdRoute
  '/portal/tutor/availability': typeof PortalTutorAvailabilityRoute
  '/portal/tutor/profile': typeof PortalTutorProfileRoute
  '/portal/tutors/$tutorId': typeof PortalTutorsTutorIdRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/onboarding/': typeof PortalOnboardingIndexRoute
  '/portal/students/': typeof PortalStudentsIndexRoute
  '/portal/tutor/': typeof PortalTutorIndexRoute
  '/portal/tutors/': typeof PortalTutorsIndexRoute
  '/portal/admin/tutors/$tutorId': typeof PortalAdminTutorsTutorIdRoute
  '/portal/admin/tutors/': typeof PortalAdminTutorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portal'
    | '/pricing'
    | '/services'
    | '/portal/admin'
    | '/portal/dashboard'
    | '/portal/logout'
    | '/portal/tutor'
    | '/portal/'
    | '/portal/forgot-password/$'
    | '/portal/login/$'
    | '/portal/onboarding/payment'
    | '/portal/onboarding/student'
    | '/portal/register/$'
    | '/portal/settings/account'
    | '/portal/students/$studentId'
    | '/portal/tutor/availability'
    | '/portal/tutor/profile'
    | '/portal/tutors/$tutorId'
    | '/portal/admin/'
    | '/portal/onboarding/'
    | '/portal/students/'
    | '/portal/tutor/'
    | '/portal/tutors/'
    | '/portal/admin/tutors/$tutorId'
    | '/portal/admin/tutors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/services'
    | '/portal/dashboard'
    | '/portal/logout'
    | '/portal'
    | '/portal/forgot-password/$'
    | '/portal/login/$'
    | '/portal/onboarding/payment'
    | '/portal/onboarding/student'
    | '/portal/register/$'
    | '/portal/settings/account'
    | '/portal/students/$studentId'
    | '/portal/tutor/availability'
    | '/portal/tutor/profile'
    | '/portal/tutors/$tutorId'
    | '/portal/admin'
    | '/portal/onboarding'
    | '/portal/students'
    | '/portal/tutor'
    | '/portal/tutors'
    | '/portal/admin/tutors/$tutorId'
    | '/portal/admin/tutors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portal'
    | '/pricing'
    | '/services'
    | '/portal/admin'
    | '/portal/dashboard'
    | '/portal/logout'
    | '/portal/tutor'
    | '/portal/'
    | '/portal/forgot-password/$'
    | '/portal/login/$'
    | '/portal/onboarding/payment'
    | '/portal/onboarding/student'
    | '/portal/register/$'
    | '/portal/settings/account'
    | '/portal/students/$studentId'
    | '/portal/tutor/availability'
    | '/portal/tutor/profile'
    | '/portal/tutors/$tutorId'
    | '/portal/admin/'
    | '/portal/onboarding/'
    | '/portal/students/'
    | '/portal/tutor/'
    | '/portal/tutors/'
    | '/portal/admin/tutors/$tutorId'
    | '/portal/admin/tutors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tutor': {
      id: '/portal/tutor'
      path: '/tutor'
      fullPath: '/portal/tutor'
      preLoaderRoute: typeof PortalTutorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logout': {
      id: '/portal/logout'
      path: '/logout'
      fullPath: '/portal/logout'
      preLoaderRoute: typeof PortalLogoutRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tutors/': {
      id: '/portal/tutors/'
      path: '/tutors'
      fullPath: '/portal/tutors/'
      preLoaderRoute: typeof PortalTutorsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tutor/': {
      id: '/portal/tutor/'
      path: '/'
      fullPath: '/portal/tutor/'
      preLoaderRoute: typeof PortalTutorIndexRouteImport
      parentRoute: typeof PortalTutorRoute
    }
    '/portal/students/': {
      id: '/portal/students/'
      path: '/students'
      fullPath: '/portal/students/'
      preLoaderRoute: typeof PortalStudentsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding/': {
      id: '/portal/onboarding/'
      path: '/onboarding'
      fullPath: '/portal/onboarding/'
      preLoaderRoute: typeof PortalOnboardingIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/': {
      id: '/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof PortalAdminIndexRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/tutors/$tutorId': {
      id: '/portal/tutors/$tutorId'
      path: '/tutors/$tutorId'
      fullPath: '/portal/tutors/$tutorId'
      preLoaderRoute: typeof PortalTutorsTutorIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tutor/profile': {
      id: '/portal/tutor/profile'
      path: '/profile'
      fullPath: '/portal/tutor/profile'
      preLoaderRoute: typeof PortalTutorProfileRouteImport
      parentRoute: typeof PortalTutorRoute
    }
    '/portal/tutor/availability': {
      id: '/portal/tutor/availability'
      path: '/availability'
      fullPath: '/portal/tutor/availability'
      preLoaderRoute: typeof PortalTutorAvailabilityRouteImport
      parentRoute: typeof PortalTutorRoute
    }
    '/portal/students/$studentId': {
      id: '/portal/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/portal/students/$studentId'
      preLoaderRoute: typeof PortalStudentsStudentIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings/account': {
      id: '/portal/settings/account'
      path: '/settings/account'
      fullPath: '/portal/settings/account'
      preLoaderRoute: typeof PortalSettingsAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/register/$': {
      id: '/portal/register/$'
      path: '/register/$'
      fullPath: '/portal/register/$'
      preLoaderRoute: typeof PortalRegisterSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding/student': {
      id: '/portal/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/portal/onboarding/student'
      preLoaderRoute: typeof PortalOnboardingStudentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding/payment': {
      id: '/portal/onboarding/payment'
      path: '/onboarding/payment'
      fullPath: '/portal/onboarding/payment'
      preLoaderRoute: typeof PortalOnboardingPaymentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login/$': {
      id: '/portal/login/$'
      path: '/login/$'
      fullPath: '/portal/login/$'
      preLoaderRoute: typeof PortalLoginSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/forgot-password/$': {
      id: '/portal/forgot-password/$'
      path: '/forgot-password/$'
      fullPath: '/portal/forgot-password/$'
      preLoaderRoute: typeof PortalForgotPasswordSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/tutors/': {
      id: '/portal/admin/tutors/'
      path: '/tutors'
      fullPath: '/portal/admin/tutors/'
      preLoaderRoute: typeof PortalAdminTutorsIndexRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/tutors/$tutorId': {
      id: '/portal/admin/tutors/$tutorId'
      path: '/tutors/$tutorId'
      fullPath: '/portal/admin/tutors/$tutorId'
      preLoaderRoute: typeof PortalAdminTutorsTutorIdRouteImport
      parentRoute: typeof PortalAdminRoute
    }
  }
}

interface PortalAdminRouteChildren {
  PortalAdminIndexRoute: typeof PortalAdminIndexRoute
  PortalAdminTutorsTutorIdRoute: typeof PortalAdminTutorsTutorIdRoute
  PortalAdminTutorsIndexRoute: typeof PortalAdminTutorsIndexRoute
}

const PortalAdminRouteChildren: PortalAdminRouteChildren = {
  PortalAdminIndexRoute: PortalAdminIndexRoute,
  PortalAdminTutorsTutorIdRoute: PortalAdminTutorsTutorIdRoute,
  PortalAdminTutorsIndexRoute: PortalAdminTutorsIndexRoute,
}

const PortalAdminRouteWithChildren = PortalAdminRoute._addFileChildren(
  PortalAdminRouteChildren,
)

interface PortalTutorRouteChildren {
  PortalTutorAvailabilityRoute: typeof PortalTutorAvailabilityRoute
  PortalTutorProfileRoute: typeof PortalTutorProfileRoute
  PortalTutorIndexRoute: typeof PortalTutorIndexRoute
}

const PortalTutorRouteChildren: PortalTutorRouteChildren = {
  PortalTutorAvailabilityRoute: PortalTutorAvailabilityRoute,
  PortalTutorProfileRoute: PortalTutorProfileRoute,
  PortalTutorIndexRoute: PortalTutorIndexRoute,
}

const PortalTutorRouteWithChildren = PortalTutorRoute._addFileChildren(
  PortalTutorRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRouteWithChildren
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLogoutRoute: typeof PortalLogoutRoute
  PortalTutorRoute: typeof PortalTutorRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
  PortalForgotPasswordSplatRoute: typeof PortalForgotPasswordSplatRoute
  PortalLoginSplatRoute: typeof PortalLoginSplatRoute
  PortalOnboardingPaymentRoute: typeof PortalOnboardingPaymentRoute
  PortalOnboardingStudentRoute: typeof PortalOnboardingStudentRoute
  PortalRegisterSplatRoute: typeof PortalRegisterSplatRoute
  PortalSettingsAccountRoute: typeof PortalSettingsAccountRoute
  PortalStudentsStudentIdRoute: typeof PortalStudentsStudentIdRoute
  PortalTutorsTutorIdRoute: typeof PortalTutorsTutorIdRoute
  PortalOnboardingIndexRoute: typeof PortalOnboardingIndexRoute
  PortalStudentsIndexRoute: typeof PortalStudentsIndexRoute
  PortalTutorsIndexRoute: typeof PortalTutorsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRouteWithChildren,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLogoutRoute: PortalLogoutRoute,
  PortalTutorRoute: PortalTutorRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
  PortalForgotPasswordSplatRoute: PortalForgotPasswordSplatRoute,
  PortalLoginSplatRoute: PortalLoginSplatRoute,
  PortalOnboardingPaymentRoute: PortalOnboardingPaymentRoute,
  PortalOnboardingStudentRoute: PortalOnboardingStudentRoute,
  PortalRegisterSplatRoute: PortalRegisterSplatRoute,
  PortalSettingsAccountRoute: PortalSettingsAccountRoute,
  PortalStudentsStudentIdRoute: PortalStudentsStudentIdRoute,
  PortalTutorsTutorIdRoute: PortalTutorsTutorIdRoute,
  PortalOnboardingIndexRoute: PortalOnboardingIndexRoute,
  PortalStudentsIndexRoute: PortalStudentsIndexRoute,
  PortalTutorsIndexRoute: PortalTutorsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
